enable = true                       # активация задачи
description = "job description"     # описание задачи
timeout = 60                        # таймаут выполнения в секундах
tags = []                           # теги для запуска
cwd = "cwd_folder"                  # рабочая папка
command = "executer"                # команда запуска
args = [                            # аргументы
    "arg1",
    "arg2",
    "arg3"
]
[env]                               # дополнительные переменые среды
    JOB_KEY1 = "JOB_KEY1_VALUE"
    JOB_KEY2 = "JOB_KEY2_VALUE"
    JOB_KEY3 = "${JOB_ENV_KEY3}"
[cron]                              # настройка крона
    interval = "1 * * * * *"        # интервал
    time_zone = "Europe/Moscow"     # временая зона